# Generated by Django 6.0.1 on 2026-01-29 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimento', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('cliente', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimento.estabelecimento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.funcionario')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimento.servicos')),
            ],
        ),
    ]
