# Generated by Django 6.0.1 on 2026-01-29 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0002_initial'),
        ('reserva', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_do_estabelecimento', to='estabelecimento.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_do_funcionario', to='user.funcionario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_do_servico', to='estabelecimento.servicos'),
        ),
    ]
