# Generated by Django 6.0.1 on 2026-01-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_alter_reserva_estabelecimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído')], default='Pendente', max_length=20),
        ),
    ]
