# Generated by Django 6.0.1 on 2026-01-29 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('dia_funcionamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servico', models.CharField(choices=[('Cabelo', 'Cabelo'), ('Barba', 'Barba'), ('Manicure', 'Manicure'), ('Pedicure', 'Pedicure'), ('Maquiagem', 'Maquiagem')], max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.DurationField(default=None)),
            ],
        ),
    ]
