# Generated by Django 6.0.4 on 2026-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='dia_funcionamento',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='dia_funcionamento',
            field=models.ManyToManyField(to='estabelecimento.funcionamento'),
        ),
    ]
