# Generated by Django 6.0.4 on 2026-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0003_funcionamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='dia_funcionamento',
            field=models.ManyToManyField(related_name='HorariosFuncionamento', to='estabelecimento.funcionamento'),
        ),
    ]
