# Generated by Django 6.0.4 on 2026-04-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0004_alter_estabelecimento_dia_funcionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionamento',
            name='horario_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionamento',
            name='horario_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
