# Generated by Django 6.0.4 on 2026-04-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0005_funcionamento_horario_abertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='horario_abertura',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='horario_fechamento',
        ),
    ]
