# Generated by Django 6.0.4 on 2026-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0006_remove_estabelecimento_horario_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='servicos_oferecidos',
            field=models.ManyToManyField(related_name='EstabelecimentosOferecem', to='estabelecimento.servicos'),
        ),
    ]
