# Generated by Django 6.0.4 on 2026-04-14 18:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaFuncionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('hora_fim', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('motivo', models.CharField(choices=[('Almoço', 'Almoço'), ('Fim do Expediente', 'Fim do Expediente'), ('Indisponível', 'Indisponível')], max_length=50)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.funcionario')),
            ],
        ),
    ]
