# Generated by Django 6.0.4 on 2026-04-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_ausenciafuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausenciafuncionario',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
